USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'QLGV')
BEGIN
    DROP DATABASE QLGV;
END
GO

CREATE DATABASE QLGV;
GO

USE QLGV;
GO

CREATE TABLE KHOA (
    MAKHOA VARCHAR(4) PRIMARY KEY,
    TENKHOA VARCHAR(40) NOT NULL,
    NGTLAP SMALLDATETIME,
    TRGKHOA CHAR(4)
);
GO

CREATE TABLE MONHOC (
    MAMH VARCHAR(10) PRIMARY KEY,
    TENMH VARCHAR(40) NOT NULL,
    TCLT TINYINT NOT NULL,
    TCTH TINYINT NOT NULL,
    MAKHOA VARCHAR(4) NOT NULL,
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);
GO

CREATE TABLE DIEUKIEN (
    MAMH VARCHAR(10),
    MAMH_TRUOC VARCHAR(10),
    PRIMARY KEY (MAMH, MAMH_TRUOC),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)
);
GO

CREATE TABLE GIAOVIEN (
    MAGV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40) NOT NULL,
    HOCVI VARCHAR(10),
    HOCHAM VARCHAR(10),
    GIOITINH VARCHAR(3),
    NGSINH SMALLDATETIME,
    NGVL SMALLDATETIME,
    HESO NUMERIC(4,2),
    MUCLUONG MONEY,
    MAKHOA VARCHAR(4),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);
GO

CREATE TABLE LOP (
    MALOP CHAR(3) PRIMARY KEY,
    TENLOP VARCHAR(40) NOT NULL,
    TRGLOP CHAR(5),
    SISO TINYINT NOT NULL,
    MAGVCN CHAR(4),
    FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
);
GO

CREATE TABLE HOCVIEN (
    MAHV CHAR(5) PRIMARY KEY,
    HO VARCHAR(40) NOT NULL,
    TEN VARCHAR(10) NOT NULL,
    NGSINH SMALLDATETIME,
    GIOITINH VARCHAR(3),
    NOISINH VARCHAR(40),
    MALOP CHAR(3),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);
GO

CREATE TABLE GIANGDAY (
    MALOP CHAR(3),
    MAMH VARCHAR(10),
    MAGV CHAR(4),
    HOCKY TINYINT NOT NULL,
    NAM SMALLINT NOT NULL,
    TUNGAY SMALLDATETIME,
    DENNGAY SMALLDATETIME,
    PRIMARY KEY (MALOP, MAMH, MAGV),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)
);
GO

CREATE TABLE KETQUATHI (
    MAHV CHAR(5),
    MAMH VARCHAR(10),
    LANTHI TINYINT,
    NGTHI SMALLDATETIME,
    DIEM NUMERIC(4,2),
    KQUA VARCHAR(10),
    PRIMARY KEY (MAHV, MAMH, LANTHI),
    FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);
GO
